/* Optional AI reasoning layer. Deterministic facts remain the source of truth. */
export const AI_STATUS = { OFF: 'off', LOCAL: 'local', EXTERNAL: 'external', UNAVAILABLE: 'unavailable' }
export function privacyContext(facts = {}) { const allowed = ['title','taskTitle','deadline','progress','expectedProgress','remainingMinutes','risk','priority','summary','evidence','recommendations','availableMinutes','committedMinutes','trend','goal','project']; const out={}; for(const k of allowed) if(facts[k] !== undefined && facts[k] !== null) out[k]=facts[k]; return out }
export function buildCoachContext(state, deterministic = {}) { return privacyContext({ ...deterministic, summary: deterministic.summary || 'Use only the supplied Habit OS facts.' }) }
export function validateAiResponse(response, facts = {}) { if(!response || typeof response !== 'object' || typeof response.summary !== 'string') return { valid:false, reason:'Structured AI response is missing a summary.' }; // Numeric claims are checked by the deterministic caller when facts are rendered.
  const invalidNames=Object.values(facts).filter(v=>typeof v==='string' && v.length>2 && /password|token|secret/i.test(v)); return { valid: invalidNames.length===0, reason: invalidNames.length?'Sensitive value was present in context.':null, response }
}
export function deterministicExplanation(facts = {}) { if(facts.risk && facts.progress != null && facts.expectedProgress != null) return `${facts.title || facts.taskTitle || 'This item'} is ${facts.risk} because progress is ${facts.progress}% versus ${facts.expectedProgress}% expected.`; if(facts.summary) return facts.summary; return 'Not enough data to determine this.' }
export function fallbackExplanation(facts = {}, error) { return { summary: 'AI explanation unavailable.', evidence: [deterministicExplanation(facts)], recommendations: [], provider: AI_STATUS.UNAVAILABLE, error: error ? 'provider-failure' : undefined } }
export function localExplain(facts = {}) { return { summary: deterministicExplanation(facts), evidence: Array.isArray(facts.evidence) ? facts.evidence : [], recommendations: [], provider: AI_STATUS.LOCAL, grounded: true } }
export function createSupabaseAiProvider({ supabase, endpoint, fetchImpl = fetch } = {}) { return { async explain(facts, { signal } = {}) { const { data } = await supabase.auth.getSession(); const token = data?.session?.access_token; if (!token) throw new Error('unauthorized'); return createHttpAiProvider({ endpoint: endpoint || `${supabase.supabaseUrl}/functions/v1/ai`, token, fetchImpl }).explain(facts, { signal }) } } }
export function createHttpAiProvider({ endpoint = '/api/ai', token, fetchImpl = fetch } = {}) { return { async explain(facts, { signal } = {}) { const safe = privacyContext(facts); const r = await fetchImpl(endpoint, { method: 'POST', signal, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ context: safe, allowedFields: Object.keys(safe) }) }); if (!r.ok) throw new Error(`ai-${r.status}`); const body = await r.json(); return body.result } } }
export function createAiProvider({ enabled = false, provider = null } = {}) { return { enabled, async explain(facts) { if(!enabled) return { ...localExplain(facts), provider: AI_STATUS.OFF }; const safe=privacyContext(facts); if(!provider?.explain) return fallbackExplanation(safe); try { const result=await provider.explain(safe); return validateAiResponse(result,safe).valid ? { ...result, provider: AI_STATUS.EXTERNAL } : fallbackExplanation(safe,'invalid-response') } catch (e) { return fallbackExplanation(safe,e) } } } }
