/* Rule-based habit pattern analysis. Thresholds are explicit and conservative. */
import { habitRate, habitStreak, habitBestStreak } from './stats.js'
import { eligibleOn, isDone } from './stats.js'
import { weekdayOf } from './schedule.js'
import { partOfDay, PARTS_OF_DAY, subDaysStr, todayStr } from './dates.js'
import { streakHistory } from './analytics.js'
import { workloadSeries } from './work.js'
export const PATTERN_THRESHOLDS = { weekdayObservations: 3, timeObservations: 5, comparisonObservations: 5, trendDays: 30, relationshipDays: 14 }
const pct = (done, total) => total ? Math.round(done / total * 100) : null
function windowDates(days) { const out=[]; let d=subDaysStr(todayStr(), days-1); const end=todayStr(); while(d<=end){out.push(d); d=new Date(`${d}T12:00:00`); d.setDate(d.getDate()+1); d=d.toISOString().slice(0,10)} return out }
export function weekdayPattern(state, habit, days=90) { const rows=Array.from({length:7},(_,weekday)=>({weekday,done:0,total:0,rate:null})); for(const d of windowDates(days)){const r=rows[weekdayOf(d)]; if(eligibleOn(habit,d)){r.total++; if(isDone(state,habit.id,d))r.done++}}; rows.forEach(r=>r.rate=r.total>=PATTERN_THRESHOLDS.weekdayObservations?pct(r.done,r.total):null); const valid=rows.filter(r=>r.rate!=null); return {rows,best:valid.sort((a,b)=>b.rate-a.rate)[0]||null,weakest:valid.sort((a,b)=>a.rate-b.rate)[0]||null,enough:valid.length>=2}
}
export function timePattern(state, habit, days=90) { const rows=Object.fromEntries(PARTS_OF_DAY.map(p=>[p,{part:p,done:0,total:0,rate:null}])); for(const d of windowDates(days)){if(!isDone(state,habit.id,d))continue; const at=state.checkins?.[habit.id]?.[d]?.at; if(at) {const p=partOfDay(at); if(rows[p]){rows[p].done++;rows[p].total++}}} const list=Object.values(rows); list.forEach(r=>r.rate=r.total>=PATTERN_THRESHOLDS.timeObservations?pct(r.done,r.total):null); const valid=list.filter(r=>r.rate!=null); return {rows:list,best:valid.sort((a,b)=>b.rate-a.rate)[0]||null,enough:valid.length>=1}
}
export function trendAnalysis(state, habit, days=30) { const now=habitRate(state,habit,subDaysStr(todayStr(),days-1),todayStr()); const previous=habitRate(state,habit,subDaysStr(todayStr(),days*2-1),subDaysStr(todayStr(),days)); if(now.eligible<PATTERN_THRESHOLDS.comparisonObservations||previous.eligible<PATTERN_THRESHOLDS.comparisonObservations)return {id:'INSUFFICIENT DATA',current:null,previous:null,delta:null}; const current=pct(now.done,now.eligible), prior=pct(previous.done,previous.eligible), delta=current-prior; return {id:delta>=10?'IMPROVING':delta<=-10?'DECLINING':'STABLE',current,previous,delta}
}
export function streakPattern(state, habit) { const h=streakHistory(state,habit,20); const lengths=h.runs.map(r=>r.length); if(lengths.length<2)return {enough:false,current:habitStreak(state,habit),best:habitBestStreak(state,habit),average:null,breakPoint:null}; return {enough:true,current:habitStreak(state,habit),best:habitBestStreak(state,habit),average:Math.round(lengths.reduce((a,b)=>a+b,0)/lengths.length*10)/10,breakPoint:Math.round(lengths.reduce((a,b)=>a+b,0)/lengths.length)} }
export function workloadInteraction(state, habit, days=90) { const rows=workloadSeries(state,{from:subDaysStr(todayStr(),days-1),days,now:new Date()}).rows; const groups={low:{done:0,total:0},high:{done:0,total:0}}; const loads=rows.map(r=>r.minutes).filter(Boolean).sort((a,b)=>a-b); if(loads.length< PATTERN_THRESHOLDS.comparisonObservations*2)return {enough:false,reason:'Not enough data yet.'}; const mid=loads[Math.floor(loads.length*.75)]; rows.forEach(r=>{if(!eligibleOn(habit,r.date))return; const g=r.minutes>=mid?'high':'low';groups[g].total++;if(isDone(state,habit.id,r.date))groups[g].done++}); if(groups.low.total<PATTERN_THRESHOLDS.comparisonObservations||groups.high.total<PATTERN_THRESHOLDS.comparisonObservations)return {enough:false,reason:'Not enough data yet.'}; return {enough:true,low:pct(groups.low.done,groups.low.total),high:pct(groups.high.done,groups.high.total),observation:'Completion rate is lower on high-workload days.'} }
export function habitPatterns(state, habit, options={}) { const weekday=weekdayPattern(state,habit,options.days||90), time=timePattern(state,habit,options.days||90), trend=trendAnalysis(state,habit,options.trendDays||30), streak=streakPattern(state,habit), workload=workloadInteraction(state,habit,options.days||90); return {habit,weekday,time,trend,streak,workload,enough:weekday.enough||trend.id!=='INSUFFICIENT DATA'} }
