import { beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { readFileSync } from 'node:fs'
import { workWorkspace, workView, filterWork, deadlineGroups } from '../src/components/work/workViewModel.js'
import { assignmentProgress, projectProgress, deadlineTimeline, milestoneTrack } from '../src/lib/work.js'
import { workloadByDay, scorePriority } from '../src/lib/adaptive.js'
import { itemActions, resolveItem } from '../src/lib/commandActions.js'
import { StoreProvider, STORAGE_KEY } from '../src/store.jsx'
import App from '../src/App.jsx'
import { workspaceFixture } from './workspace.fixture.js'

const { now } = vi.hoisted(() => ({ now: new Date('2026-09-08T12:00:00') }))
vi.mock('../src/lib/useNow.js', () => ({ default: () => now }))
const fixture = () => workspaceFixture(now)
const stored = () => JSON.parse(localStorage.getItem(STORAGE_KEY))
async function mount(route = 'work', state = fixture()) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  window.location.hash = `#/${route}`
  render(<StoreProvider><App /></StoreProvider>)
  await screen.findByRole('heading', { level: 1, name: 'Work' })
  return document.getElementById('work-screen')
}
async function go(route) {
  window.location.hash = `#/${route}`
  fireEvent(window, new HashChangeEvent('hashchange'))
}
beforeEach(() => { localStorage.clear(); window.scrollTo = vi.fn() })

describe('Work composition adapter', () => {
  it('resolves the canonical route, query views, invalid queries and every legacy route', () => {
    expect(workView('work')).toBe('overview')
    for (const view of ['overview', 'deliverables', 'projects', 'workload', 'deadlines']) expect(workView('work', `view=${view}`)).toBe(view)
    expect(workView('work', 'view=unknown')).toBe('overview')
    expect(workView('projects')).toBe('projects')
    expect(workView('assignments')).toBe('deliverables')
    expect(workView('workload')).toBe('workload')
    expect(workView('timeline')).toBe('deadlines')
  })
  it('joins real relationships without changing state or merging progress semantics', () => {
    const state = fixture(), before = JSON.stringify(state), model = workWorkspace(state, now)
    expect(JSON.stringify(state)).toBe(before)
    expect(model.rows.find(r => r.item.id === 'a1').status.pct).toBe(assignmentProgress(state.assignments[0]).pct)
    expect(model.rows.find(r => r.item.id === 'p1').status.pct).toBe(projectProgress(state.projects[0]).pct)
    expect(model.rows.find(r => r.item.id === 'm1').status.pct).toBe(milestoneTrack(state.projects[0])[0].own)
    expect(model.rows.find(r => r.item.id === 't2').status.pct).toBe(100)
    expect(model.rows.find(r => r.item.id === 'a1').parent.id).toBe('p1')
    expect(model.rows.find(r => r.item.id === 'a3').parent).toBeNull()
    expect(model.rows.some(r => r.item.id === 'a5')).toBe(false)
  })
  it('consolidates risk from existing deterministic sources, excluding completed work', () => {
    const state = fixture(), model = workWorkspace(state, now)
    const report = model.atRisk.find(r => r.item.id === 'a1')
    expect(report.risk).toBe(scorePriority({ ...state.assignments[0], kind: 'assignment' }, { now }).risk.id)
    expect(model.atRisk[0].risk).toBe('OVERDUE')
    expect(model.atRisk.some(r => r.item.id === 'a4')).toBe(false)
    expect(new Set(model.atRisk.map(r => r.key)).size).toBe(model.atRisk.length)
  })
  it('reuses timeline parents and calendar child markers once, including task deep links', () => {
    const state = fixture(), model = workWorkspace(state, now)
    const parents = deadlineTimeline(state, { now }).groups.flatMap(g => g.entries.map(e => e.item.id))
    for (const id of parents) expect(model.deadlines.some(r => r.item.id === id)).toBe(true)
    expect(model.deadlines.find(r => r.item.id === 't1').href).toBe('projects/p1?task=t1')
    expect(model.deadlines.find(r => r.item.id === 'm1').href).toBe('projects/p1?milestone=m1')
    expect(new Set(model.deadlines.map(r => r.key)).size).toBe(model.deadlines.length)
  })
  it('builds explicit calendar horizons, effort, highest risk and click-through filters', () => {
    const model = workWorkspace(fixture(), now)
    expect(model.horizons[0].items.map(r => r.item.id).sort()).toEqual(['a1', 't1'])
    expect(model.horizons[0].effort).toBe(234)
    expect(model.horizons[0].highest.risk).toBe('CRITICAL')
    expect(model.horizons[1].items.map(r => r.item.id).sort()).toEqual(['a3', 'm2'])
    expect(model.horizons[2].items.some(r => r.item.id === 'm1')).toBe(true)
    expect(filterWork(model.deadlines, { filter: 'soon', horizon: 'today' }, model)).toEqual(model.horizons[0].items)
    expect(model.horizons[3].items.some(r => r.item.id === 'a4')).toBe(false)
  })
  it('uses workloadByDay values verbatim, including overload and unknown capacity', () => {
    const state = fixture(), model = workWorkspace(state, now)
    expect(model.load).toEqual(workloadByDay(state, { from: '2026-09-08', days: 7, now, capacityMin: 120 }))
    expect(model.load[0].remainingMin).toBe(-150)
    state.preferences.dailyCapacityMin = null
    expect(workWorkspace(state, now).load[0].remainingMin).toBeNull()
  })
  it('supports all six filters and existing matchesQuery search', () => {
    const model = workWorkspace(fixture(), now)
    expect(filterWork(model.rows, { filter: 'all' }, model)).toHaveLength(model.rows.length)
    expect(filterWork(model.rows, { filter: 'completed' }, model).every(r => r.status.complete)).toBe(true)
    expect(filterWork(model.rows, { filter: 'overdue' }, model).map(r => r.item.id)).toEqual(['a2'])
    expect(filterWork(model.rows, { filter: 'risk' }, model)).toEqual(model.rows.filter(r => r.atRisk))
    expect(filterWork(model.rows, { filter: 'active', query: 'undated' }, model).map(r => r.item.id)).toEqual(['a6'])
    expect(filterWork(model.rows, { filter: 'active' }, model).every(r => !r.status.complete)).toBe(true)
  })
  it('groups deadlines chronologically into the requested sections', () => {
    const model = workWorkspace(fixture(), now)
    const groups = deadlineGroups(filterWork(model.deadlines, {}, model), model.today)
    expect(groups.map(g => g.label)).toEqual(['Overdue', 'Today', 'Tomorrow', 'This week', 'Later'])
    expect(groups[0].rows[0].item.id).toBe('a2')
  })
  it('resolves task ItemActions with the real parent IDs and no milestone bulk completion', () => {
    const task = resolveItem(fixture(), 'project-task', 't1')
    expect(task.entity.projectId).toBe('p1')
    expect(task.entity.milestoneId).toBe('m1')
    expect(itemActions(task.kind, task.entity).find(a => a.id === 'complete').dispatch).toEqual({ type: 'TOGGLE_TASK', projectId: 'p1', milestoneId: 'm1', taskId: 't1' })
    expect(itemActions('milestone', { id: 'm1' }).some(a => a.id === 'complete')).toBe(false)
  })
})

describe('Work routes and execution journeys', () => {
  it('opens overview with active work, risk, horizons and workload but no gallery', async () => {
    const root = await mount()
    expect(within(root).getByLabelText('Work summary')).toBeTruthy()
    expect(within(root).getByRole('heading', { name: 'Needs attention' })).toBeTruthy()
    expect(within(root).getByRole('heading', { name: 'Workload snapshot' })).toBeTruthy()
    expect(root.querySelector('.gal-grid')).toBeNull()
    expect(within(root).queryByText('Delivered paper')).toBeNull()
    fireEvent.click(within(root).getByRole('radio', { name: 'Completed', exact: true }))
    expect(await within(root).findByText('Delivered paper')).toBeTruthy()
  })
  it('switches all views with addressable links and reflects hash/back changes', async () => {
    await mount()
    const nav = screen.getByRole('navigation', { name: 'Work sections' })
    for (const [label, view] of [['Deliverables', 'deliverables'], ['Projects', 'projects'], ['Workload', 'workload'], ['Deadlines', 'deadlines']]) {
      fireEvent.click(within(nav).getByRole('link', { name: label }))
      await screen.findByRole('heading', { name: label, level: 2 })
      expect(window.location.hash).toBe(`#/work?view=${view}`)
      expect(within(nav).getByRole('link', { name: label }).getAttribute('aria-current')).toBe('page')
    }
    await go('work?view=deliverables')
    await screen.findByRole('heading', { name: 'Deliverables', level: 2 })
  })
  it.each([['projects', 'Projects'], ['assignments', 'Deliverables'], ['workload', 'Workload'], ['timeline', 'Deadlines']])('keeps legacy %s functional', async (route, title) => {
    await mount(route)
    await screen.findByRole('heading', { name: title, level: 2 })
    expect(window.location.hash).toBe(`#/${route}`)
  })
  it('navigates Today horizon to a filtered chronological view', async () => {
    const root = await mount()
    fireEvent.click(within(root.querySelector('.workspace-horizons')).getByRole('link', { name: /^Today/ }))
    await screen.findByRole('heading', { name: 'Deadlines', level: 2 })
    expect(screen.getByRole('heading', { name: 'Today', level: 3 })).toBeTruthy()
    expect(screen.queryByRole('heading', { name: 'Overdue', level: 3 })).toBeNull()
    expect(screen.queryByText('Tomorrow brief')).toBeNull()
  })
  it('filters deliverables, searches using the existing matcher, and completes via ItemActions', async () => {
    const root = await mount('work?view=deliverables')
    expect(within(root).queryByText('Delivered paper')).toBeNull()
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search work' }), { target: { value: 'DSA' } })
    expect(screen.queryByText('Overdue lab')).toBeNull()
    const row = screen.getByRole('article', { name: 'Assignment: Submit DSA report' })
    expect(within(row).getByRole('link', { name: 'Habit OS' }).getAttribute('href')).toBe('#/projects/p1')
    fireEvent.click(within(row).getByRole('button', { name: 'Complete Submit DSA report' }))
    await waitFor(() => expect(stored().assignments.find(a => a.id === 'a1').progress).toBe(100))
    fireEvent.click(screen.getByRole('radio', { name: 'Completed', exact: true }))
    expect(await screen.findByText('Submit DSA report')).toBeTruthy()
  })
  it('opens a deliverable detail with deadline/progress before subtasks and starts its own focus', async () => {
    await mount('work?view=deliverables')
    fireEvent.click(screen.getByRole('link', { name: 'View Submit DSA report' }))
    await screen.findByRole('heading', { name: 'Submit DSA report', level: 1 })
    const detail = document.getElementById('assignment-detail')
    expect(detail.textContent.indexOf('Deadline')).toBeLessThan(detail.textContent.indexOf('Next action'))
    fireEvent.click(screen.getByRole('button', { name: 'Start Focus' }))
    const dialog = await screen.findByRole('dialog', { name: 'Focus · Submit DSA report' })
    // FocusMode is a lazy chunk: await its inner <h2> (named after the item)
    // instead of a sync getByRole, which can run before the chunk mounts.
    expect(await within(dialog).findByRole('heading', { name: 'Submit DSA report' })).toBeTruthy()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Start', exact: true }))
    expect(await within(dialog).findByRole('button', { name: 'Pause' })).toBeTruthy()
  })
  it('uses list by default, keeps gallery optional and lets project work complete independently', async () => {
    const root = await mount('work?view=projects')
    expect(within(root).getByRole('radio', { name: 'List', exact: true }).getAttribute('aria-checked')).toBe('true')
    fireEvent.click(within(root).getByRole('radio', { name: 'Gallery / spatial' }))
    await waitFor(() => expect(root.querySelector('.gal-card')).toBeTruthy())
    fireEvent.click(within(root).getByRole('radio', { name: 'List', exact: true }))
    const details = root.querySelector('.workspace-project-items')
    details.open = true; fireEvent(details, new Event('toggle'))
    const row = await screen.findByRole('article', { name: 'Project task: Finish API layer' })
    fireEvent.click(within(row).getByRole('button', { name: 'Complete Finish API layer' }))
    await waitFor(() => expect(stored().projects[0].milestones[0].tasks[0].done).toBe(true))
  })
  it('opens a task deep link in its project and keeps rich detail after active work', async () => {
    await mount('work?view=deadlines')
    fireEvent.click(screen.getByRole('link', { name: 'View Finish API layer' }))
    await screen.findByRole('heading', { name: 'Habit OS', level: 1 })
    expect(window.location.hash).toBe('#/projects/p1?task=t1')
    await waitFor(() => expect(document.activeElement.id).toBe('work-task-t1'))
    expect(screen.getByRole('heading', { name: 'Next work' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Linked deliverables' })).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Mark Finish API layer done' }))
    await waitFor(() => expect(stored().projects[0].milestones[0].tasks[0].done).toBe(true))
  })
  it('synthesizes overload, opens Plan and Recover without silently rescheduling', async () => {
    const root = await mount('work?view=workload')
    expect(within(root).getAllByRole('heading', { name: /Over capacity by/ })).toHaveLength(1)
    expect(root.textContent).toContain('2h 30m')
    const before = stored().assignments.map(a => a.deadline)
    fireEvent.click(within(root.querySelector('.workspace-overload')).getByRole('button', { name: 'Plan' }))
    await screen.findByRole('dialog', { name: 'Plan work' })
    fireEvent.keyDown(document, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    fireEvent.click(screen.getByRole('button', { name: 'Recover', exact: true }))
    await screen.findByRole('dialog', { name: 'Recover capacity' })
    expect(stored().assignments.map(a => a.deadline)).toEqual(before)
  })
  it('runs Edit and Move through existing forms and confirms Delete with undo', async () => {
    await mount('work?view=deliverables')
    fireEvent.click(screen.getByRole('button', { name: 'Actions for Submit DSA report' }))
    let dialog = await screen.findByRole('dialog', { name: 'Submit DSA report' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Edit', exact: true }))
    await screen.findByRole('dialog', { name: 'Edit assignment' })
    fireEvent.keyDown(document, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    fireEvent.click(screen.getByRole('button', { name: 'Actions for Submit DSA report' }))
    dialog = await screen.findByRole('dialog', { name: 'Submit DSA report' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Delete', exact: true }))
    expect(stored().assignments.some(a => a.id === 'a1')).toBe(true)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirm delete' }))
    await waitFor(() => expect(stored().assignments.some(a => a.id === 'a1')).toBe(false))
    fireEvent.click(screen.getByRole('button', { name: 'Undo', exact: true }))
    await waitFor(() => expect(stored().assignments.some(a => a.id === 'a1')).toBe(true))
  })
  it('drills active count into all work types rather than a projects-only list', async () => {
    const root = await mount()
    fireEvent.click(within(root.querySelector('.workspace-summary')).getByRole('link', { name: /Active work/ }))
    await screen.findByRole('heading', { name: 'Work items' })
    expect(screen.getByRole('article', { name: 'Assignment: Submit DSA report' })).toBeTruthy()
    expect(screen.getByRole('article', { name: 'Project task: Finish API layer' })).toBeTruthy()
    expect(screen.getByRole('article', { name: 'Milestone: Research checkpoint' })).toBeTruthy()
  })
  it('opens Move deadline in the existing editor and requires confirmation before Archive', async () => {
    await mount('work?view=deliverables')
    fireEvent.click(screen.getByRole('button', { name: 'Actions for Submit DSA report' }))
    let dialog = await screen.findByRole('dialog', { name: 'Submit DSA report' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Move deadline' }))
    await screen.findByRole('dialog', { name: 'Edit assignment' })
    fireEvent.keyDown(document, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    fireEvent.click(screen.getByRole('button', { name: 'Actions for Submit DSA report' }))
    dialog = await screen.findByRole('dialog', { name: 'Submit DSA report' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Archive', exact: true }))
    expect(stored().assignments.find(a => a.id === 'a1').archived).toBe(false)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirm archive' }))
    await waitFor(() => expect(stored().assignments.find(a => a.id === 'a1').archived).toBe(true))
  })
  it('has a useful empty state, not empty analytics', async () => {
    const root = await mount('work', { ...fixture(), projects: [], assignments: [] })
    expect(within(root).getByRole('heading', { name: 'Your work starts here.' })).toBeTruthy()
    expect(within(root).queryByText('Workload snapshot')).toBeNull()
    fireEvent.click(within(root).getAllByRole('button', { name: 'Create work', exact: true })[0])
    await screen.findByRole('dialog', { name: 'New assignment' })
  })
  it('provides keyboard-native links, pressed filters, descriptive actions and scoped responsive structure', async () => {
    await mount('work?view=deliverables')
    const user = userEvent.setup()
    const filter = screen.getByRole('radio', { name: 'Overdue', exact: true })
    filter.focus(); await user.keyboard('{Enter}')
    await waitFor(() => expect(filter.getAttribute('aria-checked')).toBe('true'))
    expect(screen.getByRole('link', { name: 'View Overdue lab' })).toBeTruthy()
    const css = readFileSync('src/styles/workspace.css', 'utf8')
    expect(css).toContain('@media (max-width: 760px)')
    expect(css).toContain('prefers-reduced-motion: reduce')
    expect(css).toContain(':focus-visible')
    expect(css).toContain('minmax(0, 1fr)')
  })
})
